management:
  server:
    port: 80 #指定端口 ,缺省值项目端口 ,访问可以不用写出80端口,这是公认值
    servlet:
      context-path: /monitor #指定访问路径, 缺省值 /actuator
  endpoints:
    web:
      exposure:
        include: "*" #web 默认只能访问health 和info ,其他endpoints不对web开放
  #    enabled-by-default: false 关闭默认的endpoints配置
  endpoint: #使用自己设置的endpoints配置
    shutdown:
      enabled: true #缺省值 false
#    health:
#      enabled: true
#    info:
#      enabled: true
info: #自定以info ,通过 /info endpoints访问,不需要其他多余配置
  app:
    name: 我的第一个actuator
  version: 1.0.0