logging:
  file: #项目日志
    #    path: mylog #设置日志路径,/磁盘根分目录,相对当前项目和spring.file.name二者只能存在一个,默认spring.log
    name: mylog/chz.log #设置日志文件路径与名字名
  level:
    root: debug #指定根日志记录级别, 即全局
  # com.chz.controller: trace #指定包日志记录级别
    my: error
  group:
    my: [com.chz.controller, com.chz.entity]
debug: true #输出更多装配信息, 但是日志不会被设为debug level

