spring:
  thymeleaf:
    enabled: true #是否开启thymeleaf, 缺省值 开发中一般设置为false
    encoding: UTF-8 #编码 ,缺省值
    cache: true #开启模板缓存, 缺省值
    check-template: true #检查模板是否存在, 缺省值
    check-template-location: true #检查默认位置是否正确, 缺省值
    servlet:
      content-type: text/html #xml-rpc 缺省值
    excluded-view-names: #那些视图不经过thymeleaf模板
    mode: HTML #缺省值
    prefix: classpath:/templates/ #视图解析器的前缀, 缺省值
    suffix: .html #视图解析器后缀, 缺省值







